# Generated by Django 5.0.1 on 2024-04-03 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
