# Generated by Django 4.2.6 on 2024-03-29 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=255)),
                ("course_code", models.IntegerField()),
                ("crn", models.IntegerField()),
                ("department", models.CharField(max_length=255)),
                ("credit_hours", models.IntegerField()),
                ("professor", models.CharField(blank=True, max_length=255)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("start_time_2", models.TimeField(blank=True, null=True)),
                ("end_time_2", models.TimeField(blank=True, null=True)),
                ("days", models.CharField(blank=True, max_length=10, null=True)),
                ("days_2", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "enrolled_students",
                    models.ManyToManyField(
                        related_name="enrolled_courses", to="users.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                ("days_of_week", models.CharField(max_length=50)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdditionalActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Additional Activities",
            },
        ),
        migrations.CreateModel(
            name="AcademicRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(max_length=2)),
                (
                    "class_schedule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.classschedule",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Academic Records",
                "unique_together": {("class_schedule",)},
            },
        ),
    ]
