# Generated by Django 4.2.6 on 2024-03-28 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0015_remove_event_calendar_event_calendars"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="description",
        ),
        migrations.AddField(
            model_name="course",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="end_time_2",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="professor",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="course",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schedule.rule",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="start_time_2",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
