# Generated by Django 4.2.6 on 2024-04-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_remove_course_description_course_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="rule",
        ),
        migrations.AddField(
            model_name="course",
            name="days",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="days_2",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
