# Generated by Django 4.2.6 on 2024-03-29 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("due_date", models.DateField()),
                ("priority", models.IntegerField()),
                (
                    "estimated_completion_time",
                    models.DurationField(default=datetime.timedelta),
                ),
            ],
        ),
    ]
