# Generated by Django 4.2.6 on 2024-04-18 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_assignment_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="max_slot_duration",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
