# Generated by Django 5.0.1 on 2024-04-05 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignment_additional_username'),
        ('users', '0002_alter_student_enrollment_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='additional_username',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
