# Generated by Django 5.0.1 on 2024-04-11 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_remove_assignment_student_assignment_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='additional_username',
        ),
    ]
