# Generated by Django 4.2.6 on 2024-04-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_remove_course_rule_course_days_course_days_2"),
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.course",
            ),
        ),
    ]
