# Generated by Django 4.2.6 on 2024-04-18 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_assignment_owner"),
        ("users", "0002_alter_student_enrollment_year_and_more"),
        ("courses", "0003_remove_course_rule_course_days_course_days_2"),
        ("planner", "0002_timeslot_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.additionalactivity",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assignments.assignment",
            ),
        ),
        migrations.CreateModel(
            name="Planner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="planner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="planner.planner"
            ),
        ),
        migrations.DeleteModel(
            name="DailyPlanner",
        ),
    ]
