# Generated by Django 4.2.6 on 2024-04-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_timeslot_date_alter_timeslot_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="canceled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
